### ISSUE TITLE
readme/docs need to show the time it takes to load the runtime

### ISSUE THREAD

**Issue by davidbuzz** [extism/php-sdk#8] opened 2024-01-10 13:14 UTC
ie the difference in time between a php file having just 
```<?php echo 'hello world'; ?>```
...and a different php file that starts the extism sandbox, loads the smallest hello-world.wasm , executes a 'hello' function in it, reteieves its result,  prints it, and then ends the script.
I wanna see that accurate to the millisecond, with and without primed op  caches, with and without disk read times taken into account, and how it works when u do both 10000 times in quick succession... 
Also,how much ram overhead does it add? Does ram growth scale or stay flat?  
Does it behave differently executing as a php-fpm, apache, and the CLI  [three most common ways to run php]...  but most impirtantly... after all the numbers.. 
Is it fast-enough that i wont notice it being there?

writing php since the 90s.

**Comment by bhelx** [comment] 2024-01-10 23:14
Thanks for letting us know your expectations! We don't have any numbers specific for php. If you were planning on writing a script to calculate some of this yourself we'd welcome the input.

>  Also,how much ram overhead does it add? Does ram growth scale or stay flat?

Some of these things will be trickier to calculate in a generic way given that wasm modules are themselves programs and thus can be hard to predict. The code module itself on disk may be large or small it just depends on how it was written and compiled.

Extism allows you to set time and memory limits on modules though, so you can put some upper bounds on execution.

>  Is it fast-enough that i wont notice it being there?

This is pretty subjective and I'm not sure how to answer it. It can take some time to load and compile modules. There are various ways to speed things up and / or cache things. Finally how the module was written and optimized itself can matter too and depending on your use case you may or may not have much control over that.

**Comment by davidbuzz** [comment] 2024-01-10 23:19
Yup, the reason startup time matters on php is because in 95% of setups, php scripts dont 'stay running' like node/java/rust, there's usually an apache server , or nginx server, doing that part, and from the time u start running php to the time its done can be milliseconds.

**Comment by davidbuzz** [comment] 2024-01-11 00:07
ok, so I tried to get some runtime speed, and it just crashed for me. :-) 

curl https://get.extism.org/cli | sh
...
which extism 
/usr/local/bin/extism

sudo extism lib install --version git  [ as recommended in readme ]


echo "<?php echo 'hello world\n'; ?>" > hello.native.php
time php hello.native.php 
hello world\n
real	0m0.067s
user	0m0.039s
sys	0m0.028s

git clone https://github.com/extism/php-sdk
cd php-sdk
cd example
composer install
...

php index.php 
```
PHP TypeError:  FFI::cast(): Argument #2 ($ptr) must be of type FFI\CData, mixed given in .../php-sdk/src/LibExtism.php on line 1006632960
PHP Stack trace:
PHP   1. {main}() ~/php-sdk/example/index.php:0
PHP   2. Extism\Plugin->__construct($manifest = class Extism\Manifest { public $wasm = [0 => class Extism\UrlWasmSource { ... }]; public $memory = class Extism\MemoryOptions { public $max_pages = NULL }; public $allowed_hosts = []; public $allowed_paths = class stdClass {  }; public $config = class stdClass {  }; public $timeout_ms = NULL }, $with_wasi = TRUE) ~/php-sdk/example/index.php:11
PHP   3. LibExtism->extism_plugin_new($wasm = '{"wasm":[{"name":null,"hash":null,"url":"https:\\/\\/github.com\\/extism\\/plugins\\/releases\\/latest\\/download\\/count_vowels.wasm","headers":{},"method":null}],"memory":{"max_pages":null},"allowed_hosts":[],"allowed_paths":{},"config":{},"timeout_ms":null}', $wasm_size = 252, $functions = [], $n_functions = 0, $with_wasi = TRUE, $errmsg = class FFI\CData {  }) ~/php-sdk/src/Plugin.php:53
PHP   4. FFI->cast($type = 'ExtismPlugin*', $ptr = NFC) ~/php-sdk/src/LibExtism.php:61
PHP Fatal error:  Uncaught TypeError: FFI::cast(): Argument #2 ($ptr) must be of type FFI\CData, mixed given in ~/php-sdk/src/LibExtism.php:1006632960
Stack trace:
#0 ~/php-sdk/src/LibExtism.php(1006632960): FFI->cast()
#1 ~/php-sdk/src/Plugin.php(53): LibExtism->extism_plugin_new()
#2 ~/php-sdk/example/index.php(11): Extism\Plugin->__construct()
#3 {main}
  thrown in ~/php-sdk/src/LibExtism.php on line 1006632960

Fatal error: Uncaught TypeError: FFI::cast(): Argument #2 ($ptr) must be of type FFI\CData, mixed given in ~/php-sdk/src/LibExtism.php on line 1006632960

TypeError: FFI::cast(): Argument #2 ($ptr) must be of type FFI\CData, mixed given in ~/php-sdk/src/LibExtism.php on line 1006632960

Call Stack:
    0.0003     505680   1. {main}() ~/php-sdk/example/index.php:0
    0.0007     653832   2. Extism\Plugin->__construct($manifest = class Extism\Manifest { public $wasm = [0 => class Extism\UrlWasmSource { ... }]; public $memory = class Extism\MemoryOptions { public $max_pages = NULL }; public $allowed_hosts = []; public $allowed_paths = class stdClass {  }; public $config = class stdClass {  }; public $timeout_ms = NULL }, $with_wasi = TRUE) ~/php-sdk/example/index.php:11
    0.0018     675264   3. LibExtism->extism_plugin_new($wasm = '{"wasm":[{"name":null,"hash":null,"url":"https:\\/\\/github.com\\/extism\\/plugins\\/releases\\/latest\\/download\\/count_vowels.wasm","headers":{},"method":null}],"memory":{"max_pages":null},"allowed_hosts":[],"allowed_paths":{},"config":{},"timeout_ms":null}', $wasm_size = 252, $functions = [], $n_functions = 0, $with_wasi = TRUE, $errmsg = class FFI\CData {  }) ~/php-sdk/src/Plugin.php:53
    2.2577     675840   4. FFI->cast($type = 'ExtismPlugin*', $ptr = NFC) ~/php-sdk/src/LibExtism.php:61


Variables in local scope (#3):
  $errmsg = class FFI\CData {  }
  $functions = []
  $n_functions = 0
  $pluginPtr = class FFI\CData {  }
  $ptr = class FFI\CData {  }
  $wasi = 1
  $wasm = '{"wasm":[{"name":null,"hash":null,"url":"https:\\/\\/github.com\\/extism\\/plugins\\/releases\\/latest\\/download\\/count_vowels.wasm","headers":{},"method":null}],"memory":{"max_pages":null},"allowed_hosts":[],"allowed_paths":{},"config":{},"timeout_ms":null}'
  $wasm_size = 252
  $with_wasi = TRUE
```
php --version
PHP 8.2.14 (cli) (built: Dec 21 2023 20:19:50) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.14, Copyright (c), by Zend Technologies
    with Xdebug v3.3.0, Copyright (c) 2002-2023, by Derick Rethans

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.04
DISTRIB_CODENAME=lunar
DISTRIB_DESCRIPTION="Ubuntu 23.04"

**Comment by davidbuzz** [comment] 2024-01-11 08:58
What do u think of this..?   https://github.com/davidbuzz/PHP-CPP/tree/master/Examples/extism

**Comment by mhmd-azeez** [comment] 2024-01-11 17:55
@davidbuzz can you please provide us the source code for `~/php-sdk/example/index.php`?

**Comment by mhmd-azeez** [comment] 2024-01-11 17:58
@davidbuzz I did a fresh clone and install of extism, but can't reproduce the crash:

```
❯ php index.php
string(43) "{"count":3,"total":3,"vowels":"aeiouAEIOU"}"
string(45) "{"count":4,"total":4,"vowels":"aeiouyAEIOUY"}"
❯ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

**Comment by davidbuzz** [comment] 2024-01-11 22:11
there's a few differences here. eg, I'm running 23.04 not 22.04, also I have very recently done a 'sudo extism lib install latest' which I suspect u have not. 
can u please re-try with these steps..?
sudo extism lib install latest
```
Installing v1.0.0 to /usr/local
Fetching https://github.com/extism/extism/releases/download/v1.0.0/libextism-x86_64-unknown-linux-gnu-v1.0.0.tar.gz
Copying extism.h to /usr/local/include/extism.h
Copying libextism.so to /usr/local/lib/libextism.so
Copying libextism.a to /usr/local/lib/libextism.a
Copying extism.pc.in to /usr/local/lib/pkgconfig/extism.pc
Copying extism-static.pc.in to /usr/local/lib/pkgconfig/extism-static.pc
```

php --version
```
PHP 8.2.14 (cli) (built: Dec 21 2023 20:19:50) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.14, Copyright (c), by Zend Technologies
    with Xdebug v3.3.0, Copyright (c) 2002-2023, by Derick Rethans
```

cd ~/php-sdk/example
index.php
```
[ error as per above ]
```
I also have a few other php modules installed like xdebug and oci8 , but these unlikely to be the issue.
ls -lrt /usr/lib/php/20220829/
```
total 18016
-rw-r--r-- 1 root root   60872 Nov 25 23:08 ast.so
-rw-r--r-- 1 root root   51496 Nov 25 23:27 mcrypt.so
-rw-r--r-- 1 root root 2440776 Nov 25 23:32 mongodb.so
-rw-r--r-- 1 root root 2027576 Dec  1 06:11 xdebug.so
-rw-r--r-- 1 root root  706424 Dec 21 15:54 oci8.so
-rw-r--r-- 1 root root   96520 Dec 22 06:19 zip.so
-rw-r--r-- 1 root root   39176 Dec 22 06:19 xsl.so
-rw-r--r-- 1 root root   51464 Dec 22 06:19 xmlwriter.so
-rw-r--r-- 1 root root   59656 Dec 22 06:19 xml.so
-rw-r--r-- 1 root root   47368 Dec 22 06:19 xmlreader.so
-rw-r--r-- 1 root root   35080 Dec 22 06:19 tokenizer.so
-rw-r--r-- 1 root root   22792 Dec 22 06:19 sysvshm.so
-rw-r--r-- 1 root root   14600 Dec 22 06:19 sysvsem.so
-rw-r--r-- 1 root root   22792 Dec 22 06:19 sysvmsg.so
-rw-r--r-- 1 root root  104712 Dec 22 06:19 sockets.so
-rw-r--r-- 1 root root  338184 Dec 22 06:19 soap.so
-rw-r--r-- 1 root root   63752 Dec 22 06:19 simplexml.so
-rw-r--r-- 1 root root   18696 Dec 22 06:19 shmop.so
-rw-r--r-- 1 root root   39176 Dec 22 06:19 readline.so
-rw-r--r-- 1 root root   43272 Dec 22 06:19 posix.so
-rw-r--r-- 1 root root  289032 Dec 22 06:19 phar.so
-rw-r--r-- 1 root root  133384 Dec 22 06:19 pdo.so
-rw-r--r-- 1 root root   35080 Dec 22 06:19 pdo_odbc.so
-rw-r--r-- 1 root root   35080 Dec 22 06:19 pdo_mysql.so
-rw-r--r-- 1 root root 1023016 Dec 22 06:19 opcache.so
-rw-r--r-- 1 root root   80136 Dec 22 06:19 odbc.so
-rw-r--r-- 1 root root  231280 Dec 22 06:19 mysqlnd.so
-rw-r--r-- 1 root root  166152 Dec 22 06:19 mysqli.so
-rw-r--r-- 1 root root 1196960 Dec 22 06:19 mbstring.so
-rw-r--r-- 1 root root  100616 Dec 22 06:19 ldap.so
-rw-r--r-- 1 root root  588128 Dec 22 06:19 intl.so
-rw-r--r-- 1 root root   51464 Dec 22 06:19 iconv.so
-rw-r--r-- 1 root root   71944 Dec 22 06:19 gmp.so
-rw-r--r-- 1 root root   18696 Dec 22 06:19 gettext.so
-rw-r--r-- 1 root root  112904 Dec 22 06:19 gd.so
-rw-r--r-- 1 root root   71944 Dec 22 06:19 ftp.so
-rw-r--r-- 1 root root 7153984 Dec 22 06:19 fileinfo.so
-rw-r--r-- 1 root root  178440 Dec 22 06:19 ffi.so
-rw-r--r-- 1 root root   96520 Dec 22 06:19 exif.so
-rw-r--r-- 1 root root  198920 Dec 22 06:19 dom.so
-rw-r--r-- 1 root root  125192 Dec 22 06:19 curl.so
-rw-r--r-- 1 root root   14600 Dec 22 06:19 ctype.so
-rw-r--r-- 1 root root   35080 Dec 22 06:19 calendar.so
-rw-r--r-- 1 root root   30984 Dec 22 06:19 bz2.so
-rw-r--r-- 1 root root   39176 Dec 22 06:19 bcmath.so
drwxr-xr-x 2 root root    4096 Jan  5 10:58 build
```

**Comment by davidbuzz** [comment] 2024-01-11 22:12
I suspect u haven't got the latest 1.0.0 release from a few days ago..? with: sudo extism lib install latest

**Comment by davidbuzz** [comment] 2024-01-11 22:13
... or your php version is older.

**Comment by bhelx** [comment] 2024-01-12 01:26
> https://github.com/davidbuzz/PHP-CPP/tree/master/Examples/extism

Thanks for looking at alternative ways to integrate with libextism! I think this is an interesting strategy. It makes sense that FFI is slower. I'll try it out and study it to see how it works.

**Comment by bhelx** [comment] 2024-01-12 01:30
Also I should note, i couldn't get the crash either. I ran the example here: https://github.com/extism/php-sdk/tree/main/example

Though I'm on a mac and haven't tried on linux yet

```
php --version
PHP 8.3.0 (cli) (built: Nov 24 2023 13:21:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.0, Copyright (c), by Zend Technologies
```

**Comment by davidbuzz** [comment] 2024-01-12 03:22
I have identified the root cause of my crash...  https://bugs.xdebug.org/2224 , which isn't actually a bug in xdebug, its a bug in php itself..  https://github.com/php/php-src/issues/12905   
I did this by doing this first:
sudo mv /usr/lib/php/20230831/xdebug.so /usr/lib/php/20230831/xdebug.so.t
running the 'php index.php' as above, and getting wasm output ( and a warning that xdebug couldn't load, obv )..
php index.php 
PHP Warning:  Failed loading Zend extension 'xdebug.so' (tried: /usr/lib/php/20230831/xdebug.so (/usr/lib/php/20230831/xdebug.so: cannot open shared object file: No such file or directory), 
string(43) "{"count":3,"total":3,"vowels":"aeiouAEIOU"}"
string(45) "{"count":4,"total":4,"vowels":"aeiouyAEIOUY"}"

my xdebug version being 3.3.1 and the bug report says it affects php8.2 and php8.3 and was identified and fixed in the php sources for these branches about 3 weeks ago on the 9th dec, so any old php8.2 or php8.3 should be affected...  and any newer releass of them ok...  in this case these release/s forward should be ok:
8.2.15 or newer
8.3.2 or newer

I was in my initial test running 8.2.14+xdebug thus me hitting it.
You guys/gals were presumably not using xdebug, so didn't hit the issue. (u should, its usually awesome)

8.3.1 and 8.2.14 won't have the fix, as they both were released 3 days before the fix went it.

**Comment by davidbuzz** [comment] 2024-01-12 04:05
compiled php 8.3.3-dev from sources , which should have the above https://github.com/php/php-src/issues/12905 in it, and with xdebug enabled I still get the FFI::cast() error as first documented , sorry, I tried.

php --version
```
PHP 8.3.3-dev (cli) (built: Jan 12 2024 13:59:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.3-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.1, Copyright (c), by Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans
[buzz@qbi-buzz example]$ php index.php 
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port).
PHP TypeError:  FFI::cast(): Argument #2 ($ptr) must be of type FFI\CData, mixed given in /home/buzz/extism-php/php-sdk/src/LibExtism.php on line 1006632960
PHP Stack trace:
PHP   1. {main}() /home/buzz/extism-php/php-sdk/example/index.php:0
PHP   2. Extism\Plugin->__construct($manifest = class Extism\Manifest { public $wasm = [0 => class Extism\UrlWasmSource { ... }]; public $memory = class Extism\MemoryOptions { public $max_pages = NULL }; public $allowed_hosts = []; public $allowed_paths = class stdClass {  }; public $config = class stdClass {  }; public $timeout_ms = NULL }, $with_wasi = TRUE) /home/buzz/extism-php/php-sdk/example/index.php:11
PHP   3. LibExtism->extism_plugin_new($wasm = '{"wasm":[{"name":null,"hash":null,"url":"https:\\/\\/github.com\\/extism\\/plugins\\/releases\\/latest\\/download\\/count_vowels.wasm","headers":{},"method":null}],"memory":{"max_pages":null},"allowed_hosts":[],"allowed_paths":{},"config":{},"timeout_ms":null}', $wasm_size = 252, $functions = [], $n_functions = 0, $with_wasi = TRUE, $errmsg = class FFI\CData {  }) /home/buzz/extism-php/php-sdk/src/Plugin.php:53
PHP   4. FFI->cast($type = 'ExtismPlugin*', $ptr = NFC) /home/buzz/extism-php/php-sdk/src/LibExtism.php:61
PHP Fatal error:  Uncaught TypeError: FFI::cast(): Argument #2 ($ptr) must be of type FFI\CData, mixed given in /home/buzz/extism-php/php-sdk/src/LibExtism.php:1006632960
Stack trace:
#0 /home/buzz/extism-php/php-sdk/src/LibExtism.php(1006632960): FFI->cast()
#1 /home/buzz/extism-php/php-sdk/src/Plugin.php(53): LibExtism->extism_plugin_new()
#2 /home/buzz/extism-php/php-sdk/example/index.php(11): Extism\Plugin->__construct()
#3 {main}
  thrown in /home/buzz/extism-php/php-sdk/src/LibExtism.php on line 1006632960

Fatal error: Uncaught TypeError: FFI::cast(): Argument #2 ($ptr) must be of type FFI\CData, mixed given in /home/buzz/extism-php/php-sdk/src/LibExtism.php on line 1006632960

TypeError: FFI::cast(): Argument #2 ($ptr) must be of type FFI\CData, mixed given in /home/buzz/extism-php/php-sdk/src/LibExtism.php on line 1006632960

Call Stack:
    0.0004     494568   1. {main}() /home/buzz/extism-php/php-sdk/example/index.php:0
    0.0011     634528   2. Extism\Plugin->__construct($manifest = class Extism\Manifest { public $wasm = [0 => class Extism\UrlWasmSource { ... }]; public $memory = class Extism\MemoryOptions { public $max_pages = NULL }; public $allowed_hosts = []; public $allowed_paths = class stdClass {  }; public $config = class stdClass {  }; public $timeout_ms = NULL }, $with_wasi = TRUE) /home/buzz/extism-php/php-sdk/example/index.php:11
    0.0018     657968   3. LibExtism->extism_plugin_new($wasm = '{"wasm":[{"name":null,"hash":null,"url":"https:\\/\\/github.com\\/extism\\/plugins\\/releases\\/latest\\/download\\/count_vowels.wasm","headers":{},"method":null}],"memory":{"max_pages":null},"allowed_hosts":[],"allowed_paths":{},"config":{},"timeout_ms":null}', $wasm_size = 252, $functions = [], $n_functions = 0, $with_wasi = TRUE, $errmsg = class FFI\CData {  }) /home/buzz/extism-php/php-sdk/src/Plugin.php:53
    1.3867     658288   4. FFI->cast($type = 'ExtismPlugin*', $ptr = NFC) /home/buzz/extism-php/php-sdk/src/LibExtism.php:61


Variables in local scope (#3):
  $errmsg = class FFI\CData {  }
  $functions = []
  $n_functions = 0
  $pluginPtr = class FFI\CData {  }
  $ptr = class FFI\CData {  }
  $wasi = 1
  $wasm = '{"wasm":[{"name":null,"hash":null,"url":"https:\\/\\/github.com\\/extism\\/plugins\\/releases\\/latest\\/download\\/count_vowels.wasm","headers":{},"method":null}],"memory":{"max_pages":null},"allowed_hosts":[],"allowed_paths":{},"config":{},"timeout_ms":null}'
  $wasm_size = 252
  $with_wasi = TRUE
```

**Comment by davidbuzz** [comment] 2024-01-12 08:41
I believe the reason xdebug has issues with this is because "Calling [FFI::cast()](https://www.php.net/manual/en/ffi.cast.php), [FFI::new()](https://www.php.net/manual/en/ffi.new.php), and [FFI::type()](https://www.php.net/manual/en/ffi.type.php) statically is now deprecated." - in 8.3, and the deprecation of these interfaces messes with something in xdebug.?

https://www.php.net/manual/en/migration83.deprecated.php  ( search that page for ffi and find the above words )  - just speculation at this point. 

I think at some point you're probably gonna have to re-write the static calls in your codebase that are using 'FFI::type()' and 'FFI::new()' due to that deprecation.. and when u do, there's a good chance  this xdebug/php/extism hell will go away.

**Comment by nilslice** [comment] 2024-01-12 22:02
> What do u think of this..? https://github.com/davidbuzz/PHP-CPP/tree/master/Examples/extism

This is really interesting.. going to spend some time with it internally and see how we can use it! Thanks for doing this!

**Comment by davidbuzz** [comment] 2024-01-29 01:01
given that the FFI depreciations are merged, and the incompat with xdebug should be fixed, I think this issue only really needs to solve the thing I originally opened it for at this stage... for the README to have information about how fast/slow the interface is and wether using it from apache/nginx is a plausible use-case or not.

**Comment by mhmd-azeez** [comment] 2024-01-29 15:36
@davidbuzz initializing a plugin 100 times (including reading the file from disk) and calling a function 1000 times (100k total function calls), takes `1983 ms` on my machine (13th Gen Intel(R) Core(TM) i7-1365U):

```php
<?php
use Extism\PathWasmSource;
use Extism\Manifest;
use Extism\Plugin;
use Extism\HostFunction;
use Extism\ExtismValType;
use Extism\CurrentPlugin;

require_once __DIR__ . "/../src/Plugin.php";
require_once __DIR__ . "/../src/HostFunction.php";

$wasm = new PathWasmSource(__DIR__ . "/../wasm/count_vowels_kvstore.wasm");
$manifest = new Manifest($wasm);

for ($i = 0; $i < 100; $i++){
    $kvstore = [];

    $kvRead = new HostFunction("kv_read", [ExtismValType::I64], [ExtismValType::I64], function (CurrentPlugin $p, string $key) use (&$kvstore) {
        return $kvstore[$key] ?? "\0\0\0\0";
    });

    $kvWrite = new HostFunction("kv_write", [ExtismValType::I64, ExtismValType::I64], [], function (string $key, string $value) use (&$kvstore) {
        $kvstore[$key] = $value;
    });

    $plugin = new Plugin($manifest, true, [$kvRead, $kvWrite]);

    for ($j = 0; $j < 1000; $j++){
        $output = $plugin->call("count_vowels", "Hello World!");
    }
}
```

```ps
> Measure-Command { php .\bench.php }

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 983
Ticks             : 19833147
TotalDays         : 2.295503125E-05
TotalHours        : 0.00055092075
TotalMinutes      : 0.033055245
TotalSeconds      : 1.9833147
TotalMilliseconds : 1983.3147
```

You can also run the code above to see if the performance characteristics work for your scenario. This is the [wasm file](https://github.com/extism/php-sdk/blob/main/wasm/count_vowels_kvstore.wasm) used in the test.

**Comment by neuronicnobody** [comment] 2024-06-24 17:30
@davidbuzz Closing this issue for now. Please feel free to open again if the info above doesn't address your concerns

**Closed as completed by neuronicnobody** 2024-06-24 17:30 UTC
